import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import Footer from './components/commons/layout/footer/footerContainer';
import Header from './components/commons/layout/header/headerContainer';
import Globals from './globals';

export const notoSansKR = Noto_Sans_KR({
  variable: '--font-noto-sans',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKR.variable}`}>
        <Globals />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
